@id =cmgp08pyc0001p6phy5xbu0xu

### get data agama
GET {{url}}/api/v1/master/agama?page=1&limit=10?
Content-Type: application/json
Authorization: Bearer {{token}}


### post agama
POST {{url}}/api/v1/master/agama
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nama_agama": null
}

### put agama
PUT {{url}}/api/v1/master/agama/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nama_agama": "Kristen"
}

### delete agama
DELETE {{url}}/api/v1/master/agama/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}